// #Misfits Add - Code-behind for the Group panel GUI.
// Handles member list display, pending-invite banner, leader controls visibility,
// and fires events back to GroupClientSystem.

using System.Linq;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;

namespace Content.Client._Misfits.Group.UI;

/// <summary>
/// Group panel window. Allows players to create/manage their group,
/// invite members by character name, toggle the [ALLY] overlay, and leave/disband.
/// All validation is server-side; this window only collects input and shows feedback.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class GroupWindow : FancyWindow
{
    // ── Events fired back to GroupClientSystem ─────────────────────────────

    /// <summary>Player clicked "Create Group".</summary>
    public event Action? OnCreate;

    /// <summary>Player submitted an invite. Arg: character name.</summary>
    public event Action<string>? OnInvite;

    /// <summary>Player accepted the pending invite.</summary>
    public event Action? OnAcceptInvite;

    /// <summary>Player declined the pending invite.</summary>
    public event Action? OnDeclineInvite;

    /// <summary>Player clicked Leave / Disband.</summary>
    public event Action? OnLeave;

    /// <summary>Player clicked Kick. Arg: character name.</summary>
    public event Action<string>? OnKick;

    /// <summary>Player toggled the [ALLY] overlay checkbox. Arg: whether it is now enabled.</summary>
    public event Action<bool>? OnToggleOverlay;

    // ── Constructor ────────────────────────────────────────────────────────

    public GroupWindow()
    {
        RobustXamlLoader.Load(this);

        CreateGroupButton.OnPressed  += _ => OnCreate?.Invoke();
        AcceptInviteButton.OnPressed += _ => OnAcceptInvite?.Invoke();
        DeclineInviteButton.OnPressed += _ => OnDeclineInvite?.Invoke();
        LeaveButton.OnPressed        += _ => OnLeave?.Invoke();

        InviteButton.OnPressed += _ =>
        {
            var name = InviteNameEdit.Text.Trim();
            if (string.IsNullOrEmpty(name))
                return;
            OnInvite?.Invoke(name);
            InviteNameEdit.Text = string.Empty;
        };

        KickButton.OnPressed += _ =>
        {
            var name = KickNameEdit.Text.Trim();
            if (string.IsNullOrEmpty(name))
                return;
            OnKick?.Invoke(name);
            KickNameEdit.Text = string.Empty;
        };

        OverlayToggle.OnToggled += args => OnToggleOverlay?.Invoke(args.Pressed);

        // Default hide invite and leader controls; UpdateState will show them.
        InvitePanel.Visible    = false;
        InviteDivider.Visible  = false;
        LeaderControls.Visible = false;
        LeaveButton.Visible    = false;
        CreateGroupButton.Visible = true;
    }

    // ── Public API called by GroupClientSystem ─────────────────────────────

    /// <summary>
    /// Refresh window state whenever a <see cref="GroupStateUpdateEvent"/> arrives
    /// or the window is first opened.
    /// </summary>
    /// <param name="members">List of (entity, display name) pairs for all group members.</param>
    /// <param name="leaderUserId">UserId of the current group leader, or null if not in a group.</param>
    /// <param name="myUserId">The local player's UserId.</param>
    /// <param name="pendingInviteFromName">Character name of who is inviting, or null if none.</param>
    public void UpdateState(
        IReadOnlyList<(NetEntity Entity, string Name)> members,
        NetUserId?  leaderUserId,
        NetUserId?  myUserId,
        string?     pendingInviteFromName)
    {
        var inGroup = members.Count > 0;
        var isLeader = inGroup && leaderUserId.HasValue && myUserId.HasValue &&
                       leaderUserId.Value == myUserId.Value;

        // ── Pending invite banner ─────────────────────────────────────────
        var hasPendingInvite = !string.IsNullOrEmpty(pendingInviteFromName);
        InvitePanel.Visible   = hasPendingInvite;
        InviteDivider.Visible = hasPendingInvite;
        if (hasPendingInvite)
            InviteLabel.Text = Loc.GetString("group-invite-pending-label", ("name", pendingInviteFromName!));

        // ── Member list ───────────────────────────────────────────────────
        MembersContainer.RemoveAllChildren();
        if (!inGroup)
        {
            var noGroup = new Label
            {
                Text             = Loc.GetString("group-no-members-label"),
                FontColorOverride = Color.Gray,
                Margin            = new Thickness(4, 2),
            };
            MembersContainer.AddChild(noGroup);
        }
        else
        {
            foreach (var (_, name) in members)
            {
                // Mark the leader with a ★ prefix.
                var isEntryLeader = leaderUserId.HasValue &&
                    members.FirstOrDefault(m => m.Name == name).Entity != default;

                // Build label — leader name gets a teal tint.
                var entry = new Label
                {
                    Text         = name,
                    Margin       = new Thickness(4, 2),
                    ClipText     = true,
                    HorizontalExpand = true,
                };

                if (isLeader && name == members.First().Name)
                    entry.FontColorOverride = new Color(0.1f, 0.85f, 0.85f); // teal for leader

                MembersContainer.AddChild(entry);
            }
        }

        // ── Create button — visible only when NOT in group ────────────────
        CreateGroupButton.Visible = !inGroup;

        // ── Leader controls — invite/kick only for the current leader ─────
        LeaderControls.Visible = isLeader;

        // ── Leave / Disband ───────────────────────────────────────────────
        LeaveButton.Visible = inGroup;
        LeaveButton.Text = isLeader
            ? Loc.GetString("group-disband-button")
            : Loc.GetString("group-leave-button");

        StatusLabel.SetMessage(string.Empty);
    }

    /// <summary>Show a one-line feedback message (success = green, failure = red).</summary>
    public void ShowResult(bool success, string message)
    {
        var color = success ? "#55FF55" : "#FF6644";
        StatusLabel.SetMarkup($"[color={color}]{message}[/color]");
    }
}
